<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title>Clients Export</title>
    <style>
        body {
            font-family: 'Helvetica', 'Arial', sans-serif;
            font-size: 10px;
            line-height: 1.4;
            color: #333;
        }
        .header {
            text-align: center;
            margin-bottom: 20px;
            padding-bottom: 10px;
            border-bottom: 2px solid #4F46E5;
        }
        .header h1 {
            color: #4F46E5;
            margin: 0;
            font-size: 20px;
        }
        .header p {
            margin: 5px 0 0;
            color: #666;
            font-size: 10px;
        }
        .info {
            margin-bottom: 20px;
            padding: 10px;
            background: #f8f9fa;
            border-radius: 5px;
        }
        .info table {
            width: 100%;
            font-size: 9px;
        }
        .info td {
            padding: 3px;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
        }
        th {
            background: #4F46E5;
            color: white;
            padding: 8px;
            font-size: 9px;
            font-weight: bold;
            text-align: left;
        }
        td {
            padding: 6px 8px;
            border-bottom: 1px solid #e0e0e0;
            font-size: 8px;
        }
        tr:nth-child(even) {
            background: #f8f9fa;
        }
        .status-pending {
            color: #f59e0b;
            font-weight: bold;
        }
        .status-approved {
            color: #10b981;
            font-weight: bold;
        }
        .status-active {
            color: #059669;
            font-weight: bold;
        }
        .status-suspended {
            color: #f97316;
            font-weight: bold;
        }
        .status-rejected {
            color: #ef4444;
            font-weight: bold;
        }
        .footer {
            text-align: center;
            margin-top: 20px;
            padding-top: 10px;
            border-top: 1px solid #ddd;
            font-size: 8px;
            color: #666;
        }
        .badge {
            display: inline-block;
            padding: 2px 6px;
            background: #e0e7ff;
            color: #4F46E5;
            border-radius: 3px;
            font-size: 8px;
            margin: 2px;
        }
        .stats {
            display: flex;
            justify-content: space-between;
            margin-bottom: 20px;
        }
        .stat-box {
            background: #f3f4f6;
            padding: 8px;
            border-radius: 5px;
            text-align: center;
            flex: 1;
            margin: 0 5px;
        }
        .stat-box h4 {
            margin: 0;
            font-size: 10px;
            color: #4F46E5;
        }
        .stat-box p {
            margin: 5px 0 0;
            font-size: 16px;
            font-weight: bold;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>ASPN Overseas - Clients Report</h1>
        <p>Generated on: {{ $generated_at }} | Generated by: {{ $generated_by }}</p>
    </div>
    
    <!-- <div class="stats">
        <div class="stat-box">
            <h4>Total Clients</h4>
            <p>{{ $total }}</p>
        </div>
        <div class="stat-box">
            <h4>Pending</h4>
            <p>{{ $statistics['pending'] }}</p>
        </div>
        <div class="stat-box">
            <h4>Approved</h4>
            <p>{{ $statistics['approved'] }}</p>
        </div>
        <div class="stat-box">
            <h4>Active</h4>
            <p>{{ $statistics['active'] }}</p>
        </div>
        <div class="stat-box">
            <h4>Verified</h4>
            <p>{{ $statistics['verified'] }}</p>
        </div>
    </div> -->
    
    @if(!empty($filters) && (isset($filters['search']) || isset($filters['status']) || isset($filters['verification_status']) || isset($filters['industry'])))
    <div class="info">
        <table>
            <tr>
                <td width="100"><strong>Applied Filters:</strong></td>
                <td>
                    @if(!empty($filters['search'])) Search: "{{ $filters['search'] }}" @endif
                    @if(!empty($filters['status'])) | Status: {{ ucfirst($filters['status']) }} @endif
                    @if(!empty($filters['verification_status'])) | Verification: {{ ucfirst($filters['verification_status']) }} @endif
                    @if(!empty($filters['industry'])) | Industry: {{ $filters['industry'] }} @endif
                </td>
            </tr>
        </table>
    </div>
    @endif
    
    <table>
        <thead>
            <tr>
                <th>Client ID</th>
                <th>Name</th>
                <th>Organization</th>
                <th>Email</th>
                <th>Phone</th>
                <th>Industry</th>
                <th>Status</th>
                <th>Verification</th>
                <th>Registered</th>
            </tr>
        </thead>
        <tbody>
            @foreach($clients as $client)
            <tr>
                <td>{{ $client->client_id }}</td>
                <td>{{ $client->name }}</td>
                <td>{{ $client->organization_name }}</td>
                <td>{{ $client->email }}</td>
                <td>{{ $client->phone }}</td>
                <td>{{ $client->industry_type }}</td>
                <td>
                    <span class="status-{{ $client->status }}">
                        {{ ucfirst($client->status) }}
                    </span>
                </td>
                <td>
                    @if($client->verification_status == 'verified')
                        <span class="status-approved">Verified</span>
                    @elseif($client->verification_status == 'pending')
                        <span class="status-pending">Pending</span>
                    @else
                        <span class="status-rejected">Rejected</span>
                    @endif
                </td>
                <td>{{ $client->registered_at->format('d M Y') }}</td>
            </tr>
            @endforeach
        </tbody>
    </table>
    
    <div class="footer">
        <p>This report was generated automatically by ASPN Overseas System. For any queries, please contact the system administrator.</p>
    </div>
</body>
</html>