<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title>Users Export</title>
    <style>
        body {
            font-family: 'Helvetica', 'Arial', sans-serif;
            font-size: 12px;
            line-height: 1.4;
            color: #333;
        }
        .header {
            text-align: center;
            margin-bottom: 20px;
            padding-bottom: 10px;
            border-bottom: 2px solid #4F46E5;
        }
        .header h1 {
            color: #4F46E5;
            margin: 0;
            font-size: 24px;
        }
        .header p {
            margin: 5px 0 0;
            color: #666;
            font-size: 12px;
        }
        .info {
            margin-bottom: 20px;
            padding: 10px;
            background: #f8f9fa;
            border-radius: 5px;
        }
        .info table {
            width: 100%;
            font-size: 11px;
        }
        .info td {
            padding: 3px;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
        }
        th {
            background: #4F46E5;
            color: white;
            padding: 10px;
            font-size: 11px;
            font-weight: bold;
            text-align: left;
        }
        td {
            padding: 8px 10px;
            border-bottom: 1px solid #e0e0e0;
            font-size: 10px;
        }
        tr:nth-child(even) {
            background: #f8f9fa;
        }
        .status-active {
            color: #10b981;
            font-weight: bold;
        }
        .status-inactive {
            color: #ef4444;
            font-weight: bold;
        }
        .footer {
            text-align: center;
            margin-top: 20px;
            padding-top: 10px;
            border-top: 1px solid #ddd;
            font-size: 10px;
            color: #666;
        }
        .badge {
            display: inline-block;
            padding: 2px 6px;
            background: #e0e7ff;
            color: #4F46E5;
            border-radius: 3px;
            font-size: 9px;
            margin: 2px;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>ASPN Overseas - Users Report</h1>
        <p>Generated on: {{ $generated_at }} | Generated by: {{ $generated_by }}</p>
    </div>
    
    @if(!empty($filters))
    <div class="info">
        <table>
            <tr>
                <td><strong>Applied Filters:</strong></td>
                <td>
                    @if(!empty($filters['search'])) Search: "{{ $filters['search'] }}" @endif
                    @if(!empty($filters['role'])) | Role: {{ ucfirst($filters['role']) }} @endif
                    @if(!empty($filters['status'])) | Status: {{ ucfirst($filters['status']) }} @endif
                </td>
            </tr>
            <tr>
                <td><strong>Total Records:</strong></td>
                <td>{{ count($users) }}</td>
            </tr>
        </table>
    </div>
    @endif
    
    <table>
        <thead>
            <tr>
                <th>ID</th>
                <th>Name</th>
                <th>Username</th>
                <th>Email</th>
                <th>Phone</th>
                <th>Roles</th>
                <th>Status</th>
                <th>Last Login</th>
                <th>Last IP</th>
                <th>Created At</th>
            </tr>
        </thead>
        <tbody>
            @foreach($users as $user)
            <tr>
                <td>{{ $user->id }}</td>
                <td>{{ $user->name }}</td>
                <td>{{ $user->username }}</td>
                <td>{{ $user->email }}</td>
                <td>{{ $user->phone }}</td>
                <td>
                    @foreach($user->roles as $role)
                        <span class="badge">{{ ucfirst($role->name) }}</span>
                    @endforeach
                </td>
                <td>
                    <span class="status-{{ $user->is_active ? 'active' : 'inactive' }}">
                        {{ $user->is_active ? 'Active' : 'Inactive' }}
                    </span>
                </td>
                <td>{{ $user->last_login_at ? $user->last_login_at->format('Y-m-d H:i') : 'Never' }}</td>
                <td>{{ $user->last_login_ip ?? 'N/A' }}</td>
                <td>{{ $user->created_at->format('Y-m-d H:i') }}</td>
            </tr>
            @endforeach
        </tbody>
    </table>
    
    <div class="footer">
        <p>This report was generated automatically by ASPN Overseas System. For any queries, please contact the system administrator.</p>
    </div>
</body>
</html>